name: vuepress-deploy
on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:

          
  jobs2:
     #needs: jobs1
     runs-on: ubuntu-latest
     steps:
       - name: to Gitee
         uses: wearerequired/git-mirror-action@master
         env:
           SSH_PRIVATE_KEY: ${{ secrets.GITEE }}
         with:
        # 来源仓库
           source-repo: "https://github.com/schoolnote/code.git"
        # 目标仓库
           destination-repo: "git@gitee.com:schoolnote/schoolnote.git"
  jobs3:
      needs: jobs2
      runs-on: ubuntu-latest
      steps:
        - name: reload
          uses: mizuka-wu/gitee-pages-action@v1.0.0
          with:
            repository: schoolnote/schoolnote
            cookie: ${{ secrets.RELOAD }}
            branch: master
