name: vuepress-deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x
      - name: build and deploy
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.SECRETS }}
        run: |
          yarn config set registry https://r.npm.taobao.org
          yarn
          yarn docs:build
          git push -f git@second.github.com:schoolnote/schoolnote.github.io.git main

          
