name: vuepress-deploy
on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x
      - name: build and deploy
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.SECRETS }}
        run: |
          yarn config set registry https://r.npm.taobao.org
          yarn
          yarn docs:build
          cd dist
          git init
          git config user.name "schoolnote"
          git config user.email "eve.mail@qq.com"
          git add -A
          git commit -m "Auto publish by Github Actions: $(date +"%Y年%m月%d日")"
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git push -f git@github.com:schoolnote/schoolnote.github.io.git master:main

          
